DROP TABLE IF EXISTS games;
CREATE TABLE games(
    id serial,
    name VARCHAR(48) NOT NULL,
    publisher VARCHAR(23) NOT NULL,
    year      INTEGER  NOT NULL,
    path text NOT NULL,
    rating integer NOT NULL
);

INSERT INTO games(name, publisher, year, path, rating) VALUES ('007: GoldenEye','Nintendo',1997, './assets/label_n64_007goldeneye_eu.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('007: The World Is Not Enough','Electronic Arts',2000, './assets/n64_007-worldisnotenough.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('1080 Snowboarding','Nintendo',1998, './assets/n64_1080snowboarding-alt.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('A Bus Life','Activision',1999, './assets/n64_abugslife.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Aero Fighters Assault','Video System',1997, './assets/n64_aerofightersassault.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('AeroGauge','ASCII Entertainment',1998, './assets/n64_aerogauge.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Aidyn Chronicles: The First Mage','THQ',2001, './assets/n64_aidynchronicles.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('All Star Tennis 99','Ubisoft',1999, './assets/n64_airboarder64_eu.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('All-Star Baseball 2000','Acclaim',1999, './assets/n64_allstarbaseball2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('All-Star Baseball 2001','Acclaim',2000, './assets/n64_allstarbaseball2001.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('All-Star Baseball99','Acclaim',1998, './assets/n64_allstarbaseball99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Armorines: Project S.W.A.R.M.','Acclaim',1999, './assets/n64_armorines.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Army Men: Air Combat','3DO',2000, './assets/n64_armymenaircombat.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Army Men: Sarges Heroes','3DO',1999, './assets/n64_armymensargesheroes.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Army Men: Sarges Heroes 2','3DO',2000, './assets/n64_armymensargesheroes2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Asteroids Hyper 64','Crave Entertainment',1999, './assets/n64_asteroidshyper64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Automobili Lamborghini','Titus Software',1997, './assets/n64_automobililamborghini.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Banjo-Kazooie','Nintendo',1998, './assets/n64_banjokazooie.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Banjo-Tooie','Nintendo',2000, './assets/n64_banjotooie.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Bassmasters 2000','THQ',1999, './assets/n64_bassmasters2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Batman Beyond: Return of the Joker','Ubisoft',2000, './assets/n64_batmanbeyond.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('BattleTanx','3DO',1998, './assets/n64_battletanx.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('BattleTanx: Global Assault','3DO',1999, './assets/n64_battletanxglobalassault.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Battlezone: Rise of the Black Dogs','Crave Entertainment',2000, './assets/n64_battlezone_best.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Beetle Adventure Racing!','Electronic Arts',1999, './assets/n64_beetleadvracing.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Big Mountain 2000','SouthPeak Games',2000, './assets/n64_bigmountain2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Bio F.R.E.A.K.S.','Midway Games',1998, './assets/n64_biofreaks.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Blast Corps','Nintendo',1997, './assets/n64_blastcorps.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Blues Brothers 2000','Titus Software',2000, './assets/n64_bluesbrothers2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Body Harvest','Midway Games',1998, './assets/n64_bodyharvest.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Bomberman 64','Hudson Soft',1997, './assets/n64_bomberman64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Bomberman 64: The Second Attack!','Vatical Entertainment',2000, './assets/n64_bomberman642ndattack.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Bomberman Hero','Nintendo',1998, './assets/n64_bombermanhero.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Bottom of the 9th','Konami',1999, './assets/n64_bottomof9th.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Brunswick Circuit Pro Bowling','THQ',1999, './assets/n64_brunswickcircuitprobowling.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Buck Bumble','Ubisoft',1998, './assets/n64_buckbumble.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Bust-A-Move 2: Arcade Edition','Acclaim',1998, './assets/n64_bustamove2arcadeedition.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Bust-A-Move 99','Acclaim',1999, './assets/n64_bustamove99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('California Speed','Midway Games',1999, './assets/n64_californiaspeed.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Carmageddon 64','Titus Software',1999, './assets/n64_carmageddon64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Castlevania','Konami',1998, './assets/n64_castlevania.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Castlevania: Legacy of Darkness','Konami',1999, './assets/n64_castlevanialegacyofdarkness.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Chameleon Twist','Sunsoft',1997, './assets/n64_chameleontwist.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Chameleon Twist 2','Sunsoft',1999, './assets/n64_chameleontwist2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Charlie Blasts Territory','Kemco',1999, './assets/n64_charlieblaststerritory.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Chopper Attack','Midway Games',1998, './assets/n64_chopperattack.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('ClayFighter 63 1/3','Interplay Entertainment',1997, './assets/n64_clayfighter63.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('ClayFighter: Sculptors Cut','Interplay',1998, './assets/n64_clayfightersculptorscut.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Command & Conquer','Nintendo',1999, './assets/n64_commandandconquer.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Conkers Bad Fur Day','Rare',2001, './assets/n64_conkersbadfurday.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Cruisn Exotica','Midway Games',2000, './assets/n64_cruisinexotica.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Cruisn USA','Nintendo',1996, './assets/n64_cruisinusa.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Cruisn World','Nintendo',1998, './assets/n64_cruisnworld.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('CyberTiger','Electronic Arts',2000, './assets/n64_cybertiger.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Dark Rift','Vic Tokai',1997, './assets/n64_darkrift.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Deadly Arts','Konami',1998, './assets/n64_deadlyarts.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Destruction Derby 64','THQ',1999, './assets/n64_destructionderby64_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Diddy Kong Racing','Nintendo',1997, './assets/n64_diddykongracing.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Donald Duck Goin 'Qu@ckers'','Ubisoft',2000, './assets/n64_donaldduckgoingquackers.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Donkey Kong 64','Nintendo',1999, './assets/n64_donkeykong64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Doom 64','Midway Games',1997, './assets/n64_doom64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Dr. Mario 64','Nintendo',2001, './assets/n64_drmario64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Dual Heroes','Electro Brain',1998, './assets/n64_dualheroes.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Duck Dodgers Starring Daffy Duck','Infogrames',2000, './assets/n64_duckdodgers.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Duke Nukem 64','GT Interactive Software',1997, './assets/n64_dukenukem64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Duke Nukem: Zero Hour','GT Interactive',1999, './assets/n64_dukenukemzerohour.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Earthworm Jim 3D','Rockstar Games',1999, './assets/n64_earthwormjim3d.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('ECW Hardcore Revolution','Acclaim',2000, './assets/n64_ecwhardcorerevolution.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Excitebike 64','Nintendo',2000, './assets/n64_excitebike64_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Extreme-G','Acclaim',1997, './assets/n64_extremeg.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Extreme-G 2','Acclaim',1998, './assets/n64_extreme-gxg2_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('F1 Pole Position 64','Ubisoft',1997, './assets/n64_f1poleposition64_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('F-1 World Grand Prix','Video System',1998, './assets/n64_f1worldgrandprix.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('F-Zero X','Nintendo',1998, './assets/n64_f-zerox_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('FIFA 99','EA Sports',1998, './assets/n64_fifa99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('FIFA Soccer 64','EA Sports',1997, './assets/n64_fifa64_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('FIFA: Road to World Cup 98','EA Sports',1997, './assets/n64_fifa98.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Fighter Destiny 2','SouthPeak Games',2000, './assets/n64_fighterdestiny2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Fighters Destiny','Ocean Software',1998, './assets/n64_fightersdestiny.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Fighting Force 64','Crave Entertainment',1999, './assets/n64_fightingforce64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Flying Dragon','Natsume',1998, './assets/n64_flyingdragon.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Forsaken 64','Acclaim',1998, './assets/n64_forsaken.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Fox Sports College Hoops 99','Fox Interactive',1998, './assets/n64_foxsportscollegehoops99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Gauntlet Legends','Midway Games',1999, './assets/n64_gauntletlegends.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Gex 3: Deep Cover Gecko','Crave Entertainment',1999, './assets/n64_gex3deepcovergecko.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Gex 64: Enter the Gecko','Midway Games',1998, './assets/n64_gex64enterthegecko.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Glover','Hasbro Interactive',1998, './assets/n64_glover.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Goemons Great Adventure','Konami',1999, './assets/n64_goemonsgreatadventure.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Golden Nugget 64','Electronic Arts',1998, './assets/n64_goldennugget64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('GT 64: Championship Edition','Ocean Software',1998, './assets/n64_gt64championshipedition.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Harvest Moon 64','Natsume',1999, './assets/n64_harvestmoon64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Hercules: The Legendary Journeys','Titus',2000, './assets/n64_hercules.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Hexen','GT Interactive Software',1997, './assets/n64_hexen.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Hey You, Pikachu!','Nintendo',2000, './assets/n64_heyyoupikachu.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Hot Wheels Turbo Racing','Electronic Arts',1999, './assets/n64_hotwheelsturboracing.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Hybrid Heaven','Konami',1999, './assets/n64_hybridheaven.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Hydro Thunder','Midway Games',2000, './assets/n64_hydrothunder.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Iggys Reckin Balls','Acclaim',1998, './assets/n64_iggysreckinballs.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('In-Fisherman Bass Hunter 64','Take-Two',1999, './assets/n64_basshunter64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Indiana Jones and the Infernal Machine','LucasArts',2000, './assets/n64_indianajonesandtheinfernalmachine.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Indy Racing 2000','Infogrames',2000, './assets/n64_indyracing2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('International Superstar Soccer 64','Konami',1997, './assets/n64_internationalsuperstarsoccer64_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('International Superstar Soccer 2000','Konami',2000, './assets/n64_internationalsuperstarsoccer2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('International Superstar Soccer 98','Konami',1998, './assets/n64_internationalsuperstarsoccer98.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('International Track & Field 2000','Konami',2000, './assets/n64_inttrackandfield2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Jeopardy!','GameTek',1998, './assets/n64_jeopardy.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Jeremy McGrath Supercross 2000','Acclaim',2000, './assets/n64_jeremymcgsupercross2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Jet Force Gemini','Rare',1999, './assets/n64_jetforcegeminintsc.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('John Romeros Daikatana','Kemco',2000, './assets/n64_john-romero-s-daikatana.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Ken Griffey Jr.s Slugfest','Nintendo',1999, './assets/n64_kengriffeyjrslugfest.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Killer Instinct Gold','Nintendo',1996, './assets/n64_killerinstinctgold.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Kirby 64: The Crystal Shards','Nintendo',2000, './assets/n64_kirby64thecrystalshards.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Knife Edge: Nose Gunner','Kemco',1998, './assets/n64_knifeedgenosegunner.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Knockout Kings 2000','EA Sports',1999, './assets/n64_knockoutkings2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Kobe Bryant in NBA Courtside','Nintendo',1998, './assets/n64_kobebryantnbacourtside_eu.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('The Legend of Zelda: Majoras Mask','Nintendo',2000, './assets/n64_thelegendofzeldamajorasmask.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('The Legend of Zelda: Ocarina of Time','Nintendo',1998, './assets/n64_legendofzeldaocarinaoftimeplayerschoice.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Lego Racers','Lego Media',1999, './assets/n64_legoracers.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Lode Runner 3-D','Infogrames',1999, './assets/n64_loderunner3d.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mace: The Dark Age','Midway Games',1997, './assets/n64_macethedarkage.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Madden Football 64','EA Sports',1997, './assets/n64_madden64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Madden NFL 2000','EA Sports',1999, './assets/n64_madden2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Madden NFL 2001','EA Sports',2000, './assets/n64_madden2001.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Madden NFL 2002','EA Sports',2001, './assets/n64_madden2002.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Madden NFL 99','EA Sports',1998, './assets/n64_madden99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Magical Tetris Challenge','Capcom',1999, './assets/n64_magicaltetrischallenge.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Major League Baseball Featuring Ken Griffey, Jr.','Nintendo',1998, './assets/n64_majorleaguebaseballfeaturingkengriffeyjr.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mario Golf','Nintendo',1999, './assets/n64_mariogolf.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mario Kart 64','Nintendo',1997, './assets/n64_mariokart64gold.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mario Party','Nintendo',1999, './assets/n64_marioparty.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mario Party 2','Nintendo',2000, './assets/n64_marioparty2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mario Party 3','Nintendo',2001, './assets/n64_marioparty3.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mario Tennis','Nintendo',2000, './assets/n64_mariotennis.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mega Man 64','Capcom',2001, './assets/n64_megaman64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mia Hamm Soccer 64','SouthPeak Games',2000, './assets/n64_miahammsoccer64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mickeys Speedway USA','Nintendo',2000, './assets/n64_mickeysspeedwayusa_eu.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Micro Machines 64 Turbo','Midway Games',1999, './assets/n64_micromachines.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Midways Greatest Arcade Hits: Volume 1','Midway Games',2000, './assets/n64_midwaysgreatesthits.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mike Piazzas Strike Zone','GT Interactive Software',1998, './assets/n64_mikepiazzasstrikezone.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Milos Astro Lanes','Crave Entertainment',1998, './assets/n64_milosastrolanes.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mischief Makers','Nintendo',1997, './assets/n64_mischiefmakers.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mission: Impossible','Ocean Software',1998, './assets/n64_missionimpossible.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Monaco Grand Prix','Ubisoft',1999, './assets/n64_monacograndprix.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Monopoly','Hasbro Interactive',1999, './assets/n64_monopoly.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Monster Truck Madness 64','Rockstar Games',1999, './assets/n64_monstertruckmadness.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mortal Kombat 4','Midway Games',1998, './assets/n64_mortalkombat4.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mortal Kombat Mythologies: Sub-Zero','Midway Games',1997, './assets/n64_mortalkombatmythologiessubzero.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mortal Kombat Trilogy','Midway Games',1996, './assets/n64_mortalkombattrilogy.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Ms. Pac-Man: Maze Madness','Namco',2000, './assets/n64_mspacman.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Multi-Racing Championship','Ocean Software',1997, './assets/n64_mrcmultiracingchampionship.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mystical Ninja Starring Goemon','Konami',1998, './assets/n64_mysticalninja.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Mystical Ninja 2 Starring Goemon','Konami',1998, './assets/n64_mysticalninja2_eu.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Nagano Winter Olympics 98','Konami',1998, './assets/n64_naganowinterolympics98.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Namco Museum 64','Namco',1999, './assets/n64_namcomuseum64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NASCAR 2000','EA Sports',1999, './assets/n64_nascar2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NASCAR 99','EA Sports',1998, './assets/n64_nascar99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NBA Courtside 2 Featuring Kobe Bryant','Nintendo',1999, './assets/n64_nbacourtside2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NBA Hangtime','Midway Games',1997, './assets/n64_nbahangtime_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NBA In the Zone 2000','Konami',2000, './assets/n64_nbainzone2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NBA In The Zone 98','Konami',1998, './assets/n64_nbainthezone98.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NBA In The Zone 99','Konami',1999, './assets/n64_nbainthezone99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NBA Jam 2000','Acclaim',1999, './assets/n64_nbajam2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NBA Jam 99','Acclaim',1998, './assets/n64_nbajam99_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NBA Live 2000','EA Sports',1999, './assets/n64_nbalive2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NBA Live 99','EA Sports',1998, './assets/n64_nbalive99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NBA Showtime: NBA on NBC','Midway Games',1999, './assets/n64_nbashowtime.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('The New Tetris','Nintendo',1999, './assets/n64_thenewtetris.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NFL Blitz','Midway Games',1998, './assets/n64_nflblitz.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NFL Blitz 2000','Midway Games',1999, './assets/n64_nflblitz2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NFL Blitz 2001','Midway Games',2000, './assets/n64_nflblitz2001.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NFL Blitz: Special Edition','Midway Games',2001, './assets/n64_nflblitzspecialedition.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NFL Quarterback Club 98','Acclaim',1997, './assets/n64_nflqbclub98.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NFL Quarterback Club 2000','Acclaim',1999, './assets/n64_nflquarterbackclub2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NFL Quarterback Club 2001','Acclaim',2000, './assets/n64_nflqbclub2001.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NFL Quarterback Club 99','Acclaim',1998, './assets/n64_nflqbclub99_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NHL 99','EA Sports',1998, './assets/n64_nhl99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NHL Blades of Steel 99','Konami',1999, './assets/n64_nhlbladesofsteel99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NHL Breakaway 98','Acclaim',1998, './assets/n64_nhlbreakaway98.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('NHL Breakaway 99','Acclaim',1998, './assets/n64_nhlbreakaway99.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Nightmare Creatures','Activision',1998, './assets/n64_nightmarecreatures.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Nuclear Strike 64','THQ',1999, './assets/n64_nuclearstrike64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Off Road Challenge','Midway Games',1998, './assets/n64_offroadchallenge.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Ogre Battle 64: Person of Lordly Caliber','Atlus',2000, './assets/n64_ogrebattle64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Olympic Hockey 98','Midway Games',1998, './assets/n64_olympichockeynagano98.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Paper Mario','Nintendo',2001, './assets/n64_papermario.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Paperboy','Midway Games',1999, './assets/n64_paperboy.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Penny Racers','THQ',1999, './assets/n64_pennyracers_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Perfect Dark','Nintendo',2000, './assets/n64_perfectdark.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('PGA European Tour','Infogrames',2000, './assets/n64_pgaeuropeantour.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Pilotwings 64','Nintendo',1996, './assets/n64_pilotwings64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Pokemon Puzzle League','Nintendo',2000, './assets/n64_pokemonpuzzleleague.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Pokemon Snap','Nintendo',1999, './assets/n64_pokemonsnap.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Pokemon Stadium','Nintendo',2000, './assets/n64_pokemonstadium.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Pokemon Stadium 2','Nintendo',2001, './assets/n64_pokemonstadium2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Polaris SnoCross','Vatical Entertainment',2000, './assets/n64_polarissnocross.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Power Rangers: Lightspeed Rescue','THQ',2000, './assets/n64_powerrangers.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('The Powerpuff Girls: Chemical X-Traction','Bam Entertainment',2001, './assets/n64_powerpuffgirls.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Quake','Midway Games',1998, './assets/n64_quake.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Quake II','Activision',1999, './assets/n64_quakeii.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Quest 64','THQ',1998, './assets/n64_quest64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Rally Challenge 2000','SouthPeak Games',2000, './assets/n64_rallychallenge2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Rampage 2: Universal Tour','Midway Games',1999, './assets/n64_rampage2universaltourpal.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Rampage World Tour','Midway Games',1998, './assets/n64_rampageworldtour.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Rat Attack!','Mindscape',2000, './assets/n64_ratattack.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Rayman 2: The Great Escape','Ubisoft',1999, './assets/n64_rayman2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Razor Freestyle Scooter','Crave Entertainment',2001, './assets/n64_razorfreestylescooter.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Re-Volt','Acclaim',1999, './assets/n64_revolt.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Ready 2 Rumble Boxing','Midway Games',1999, './assets/n64_ready2rumbleboxing.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Ready 2 Rumble Boxing: Round 2','Midway Games',2000, './assets/n64_ready2rumbleboxinground2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Resident Evil 2','Capcom',1999, './assets/n64_residentevil2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Ridge Racer 64','Nintendo',2000, './assets/n64_ridgeracer64_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Road Rash 64','THQ',1999, './assets/n64_roadrash64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Roadsters','Titus Software',1999, './assets/n64_roadsters.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Robotron 64','Crave Entertainment',1998, './assets/n64_robotron64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Rocket: Robot on Wheels','Ubisoft',1999, './assets/n64_rocketrobotonwheels.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Rugrats in Paris: The Movie','THQ',2000, './assets/n64_rugratsinparis.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Rugrats: Scavenger Hunt','THQ',1999, './assets/n64_rugratsscavengerhunt.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Rush 2: Extreme Racing USA','Midway Games',1998, './assets/n64_rush2extremeracingusa.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('S.C.A.R.S.','Ubisoft',1998, './assets/n64_scars_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('San Francisco Rush 2049','Midway Games',2000, './assets/n64_sanfranciscorush2049.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('San Francisco Rush: Extreme Racing','Midway Games',1997, './assets/n64_sanfranciscorushextremeracing.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Scooby-Doo! Classic Creep Capers','THQ',2001, './assets/n64_scoobeydoocreepcapers.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Sesame Street: Elmos Letter Adventure','NewKidCo',1999, './assets/n64_elmosletteradventure.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Sesame Street: Elmos Number Journey','NewKidCo',1999, './assets/n64_elmosnumberjourney.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Shadow Man','Acclaim',1999, './assets/n64_shadowman.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Shadowgate 64: Trials of the Four Towers','Kemco',1999, './assets/n64_shadowgate64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Snowboard Kids','Atlus',1998, './assets/n64_snowboardkids.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Snowboard Kids 2','Atlus',1999, './assets/n64_snowboardkids2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('South Park','Acclaim',1998, './assets/n64_southpark.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('South Park Rally','Acclaim',2000, './assets/n64_southparkrally.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('South Park: Chefs Luv Shack','Acclaim',1999, './assets/n64_southparkchefsluvshack.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Space Invaders','Activision',1999, './assets/n64_spaceinvaders.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Space Station Silicon Valley','Take-Two',1998, './assets/n64_spacestationsiliconvalley.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Spider-Man','Activision',2000, './assets/n64_spiderman.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Star Fox 64','Nintendo',1997, './assets/n64_starfox64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Star Soldier: Vanishing Earth','Electro Brain',1998, './assets/n64_starsoldiervanishingearth.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Star Wars Episode I: Racer','LucasArts',1999, './assets/n64_starwars-episode1racer_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Star Wars: Episode I: Battle for Naboo','LucasArts',2000, './assets/n64_starwarsbattlefornaboo.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Star Wars: Rogue Squadron','LucasArts',1998, './assets/n64_starwars-roguesquadron_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Star Wars: Shadows of the Empire','LucasArts',1996, './assets/n64_starwars-shadowsoftheempire_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Starcraft 64','Blizzard Entertainment',2000, './assets/n64_starcraft64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Starshot: Space Circus Fever','Infogrames',1999, './assets/n64_starshotspacecircusfever.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Stunt Racer 64','Midway Games',2000, './assets/n64_stuntracer.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Super Bowling','UFO Interactive Games',2001, './assets/n64_superbowling.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Super Mario 64','Nintendo',1996, './assets/n64_supermario64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Super Smash Bros.','Nintendo',1999, './assets/n64_supersmashbros.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Supercross 2000','EA Sports',1999, './assets/n64_supercross2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Superman','Titus Software',1999, './assets/n64_superman64_eu.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Tarzan','Activision',2000, './assets/n64_tarzan.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Tetrisphere','Nintendo',1997, './assets/n64_tetrisphere_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Tiggers Honey Hunt','NewKidCo',2000, './assets/n64_tiggershoneyhunt.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Tom and Jerry in Fists of Furry','NewKidCo',2000, './assets/n64_tiggershoneyhunt.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Tom Clancys Rainbow Six','Red Storm Entertainment',1999, './assets/n64_tomclancysrainbowsix.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Tonic Trouble','Ubisoft',1999, './assets/n64_tonictrouble.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Tony Hawks Pro Skater','Activision',2000, './assets/n64_tonyhawksproskater.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Tony Hawks Pro Skater 2','Activision',2001, './assets/n64_tonyhawksproskater2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Tony Hawks Pro Skater 3','Activision',2002, './assets/n64_tonyhawksproskater3.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Top Gear Overdrive','Kemco',1998, './assets/n64_topgearoverdriventsc.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Top Gear Rally','Kemco',1997, './assets/n64_topgearrally.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Top Gear Rally 2','Kemco',1999, './assets/n64_topgearrally2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Top Gear: Hyper Bike','Kemco',2000, './assets/n64_topgearhyperbike.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Toy Story 2: Buzz Lightyear to the Rescue','Activision',1999, './assets/n64_toystory2.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Transformers: Beast Wars Transmetals','Bam Entertainment',2000, './assets/n64_transformersbeastwarstransmetal.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Triple Play 2000','EA Sports',1999, './assets/n64_tripleplay2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Turok 2: Seeds of Evil','Acclaim',1998, './assets/n64_turok2seedsofevil.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Turok 3: Shadow of Oblivion','Acclaim',2000, './assets/n64_turok3shadowofoblivion.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Turok: Dinosaur Hunter','Acclaim',1997, './assets/n64_turokdinosaurhunter.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Turok: Rage Wars','Acclaim',1999, './assets/n64_turokragewars.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Twisted Edge: Extreme Snowboarding','Midway Games',1998, './assets/n64_twistededgeextremesnowboarding.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('V-Rally Edition 99','Infogrames',1999, './assets/n64_v-rally99_au.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Vigilante 8','Activision',1998, './assets/n64_vigilante8.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Vigilante 8: 2nd Offense','Activision',2000, './assets/n64_vigilante82ndoffensive.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Virtual Chess 64','Titus Software',1998, './assets/n64_virtualchess64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Virtual Pool 64','Crave Entertainment',1998, './assets/n64_virtualpool64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Waialae Country Club: True Golf Classics','Nintendo',1998, './assets/n64_waialaecountryclubgolf.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('War Gods','Midway Games',1997, './assets/n64_wargods.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Wave Race 64','Nintendo',1996, './assets/n64_waverace64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Wayne Gretzkys 3D Hockey','Midway Games',1996, './assets/n64_waynegretzkys3dhockey.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Wayne Gretzkys 3D Hockey 98','Midway Games',1997, './assets/n64_waynegretzkys3dhockey98.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WCW Backstage Assault','Electronic Arts',2000, './assets/n64_wcwbackstageassault.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WCW Mayhem','EA Sports',1999, './assets/n64_wcwmayhem.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WCW Nitro','THQ',1999, './assets/n64_wcwnitro.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WCW vs. nWo: World Tour','THQ',1997, './assets/n64_wcwvsnwoworldtour.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WCW/nWo Revenge','THQ',1998, './assets/n64_wcwnworevenge_alt.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Wetrix','Ocean Software',1998, './assets/n64_wetrix.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Wheel of Fortune','GameTek',1997, './assets/n64_wheeloffortune.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WinBack: Covert Operations','Koei',1999, './assets/n64_winbackcovertops.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WipeOut 64','Midway Games',1998, './assets/n64_wipeout64.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('World Cup 98','EA Sports',1998, './assets/n64_worldcup98.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('World Driver Championship','Midway Games',1999, './assets/n64_worlddriverchampionship.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Worms: Armageddon','Infogrames',2000, './assets/n64_wormsarmageddon.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WWF Attitude','Acclaim',1999, './assets/n64_wwfattitude.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WWF No Mercy','THQ',2000, './assets/n64_wwfnomercy.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WWF War Zone','Acclaim',1998, './assets/n64_wwfwarzone.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('WWF WrestleMania 2000','THQ',1999, './assets/n64_wwfwrestlemania2000.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Xena: Warrior Princess - The Talisman of Fate','Titus Software',1999, './assets/n64_xenatalismanoffate.jpg', 0);
INSERT INTO games(name, publisher, year, path, rating) VALUES ('Yoshis Story','Nintendo',1998, './assets/n64_yoshisstory.jpg', 0);