INSERT INTO games(Name,Publisher,Year) VALUES ('007: GoldenEye','Nintendo',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('007: The World Is Not Enough','Electronic Arts',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('1080� Snowboarding','Nintendo',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('A Bug''s Life','Activision',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Aero Fighters Assault','Video System',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('AeroGauge','ASCII Entertainment',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Aidyn Chronicles: The First Mage','THQ',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('All Star Tennis 99','Ubisoft',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('All-Star Baseball 2000','Acclaim',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('All-Star Baseball 2001','Acclaim',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('All-Star Baseball ''99','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Armorines: Project S.W.A.R.M.','Acclaim',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Army Men: Air Combat','3DO',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Army Men: Sarge''s Heroes','3DO',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Army Men: Sarge''s Heroes 2','3DO',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Asteroids Hyper 64','Crave Entertainment',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Automobili Lamborghini','Titus Software',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Banjo-Kazooie','Nintendo',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Banjo-Tooie','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Bassmasters 2000','THQ',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Batman Beyond: Return of the Joker','Ubisoft',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('BattleTanx','3DO',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('BattleTanx: Global Assault','3DO',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Battlezone: Rise of the Black Dogs','Crave Entertainment',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Beetle Adventure Racing!','Electronic Arts',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Big Mountain 2000','SouthPeak Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Bio F.R.E.A.K.S.','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Blast Corps','Nintendo',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Blues Brothers 2000','Titus Software',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Body Harvest','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Bomberman 64','Hudson Soft',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Bomberman 64: The Second Attack!','Vatical Entertainment',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Bomberman Hero','Nintendo',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Bottom of the 9th','Konami',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Brunswick Circuit Pro Bowling','THQ',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Buck Bumble','Ubisoft',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Bust-A-Move 2: Arcade Edition','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Bust-A-Move ''99','Acclaim',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('California Speed','Midway Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Carmageddon 64','Titus Software',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Castlevania','Konami',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Castlevania: Legacy of Darkness','Konami',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Chameleon Twist','Sunsoft',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Chameleon Twist 2','Sunsoft',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Charlie Blast''s Territory','Kemco',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Chopper Attack','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('ClayFighter 63?','Interplay Entertainment',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('ClayFighter: Sculptor''s Cut','Interplay',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Command & Conquer','Nintendo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Conker''s Bad Fur Day','Rare',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Cruis''n Exotica','Midway Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Cruis''n USA','Nintendo',1996);
INSERT INTO games(Name,Publisher,Year) VALUES ('Cruis''n World','Nintendo',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('CyberTiger','Electronic Arts',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Dark Rift','Vic Tokai',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Deadly Arts','Konami',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Destruction Derby 64','THQ',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Diddy Kong Racing','Nintendo',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Donald Duck Goin'' "Qu@ckers"','Ubisoft',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Donkey Kong 64','Nintendo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Doom 64','Midway Games',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Dr. Mario 64','Nintendo',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Dual Heroes','Electro Brain',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Duck Dodgers Starring Daffy Duck','Infogrames',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Duke Nukem 64','GT Interactive Software',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Duke Nukem: Zero Hour','GT Interactive',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Earthworm Jim 3D','Rockstar Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('ECW Hardcore Revolution','Acclaim',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Excitebike 64','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Extreme-G','Acclaim',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Extreme-G 2','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('F1 Pole Position 64','Ubisoft',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('F-1 World Grand Prix','Video System',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('F-Zero X','Nintendo',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('FIFA ''99','EA Sports',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('FIFA Soccer 64','EA Sports',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('FIFA: Road to World Cup 98','EA Sports',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Fighter Destiny 2','SouthPeak Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Fighters Destiny','Ocean Software',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Fighting Force 64','Crave Entertainment',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Flying Dragon','Natsume',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Forsaken 64','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Fox Sports College Hoops ''99','Fox Interactive',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Gauntlet Legends','Midway Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Gex 3: Deep Cover Gecko','Crave Entertainment',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Gex 64: Enter the Gecko','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Glover','Hasbro Interactive',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Goemon''s Great Adventure','Konami',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Golden Nugget 64','Electronic Arts',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('GT 64: Championship Edition','Ocean Software',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Harvest Moon 64','Natsume',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Hercules: The Legendary Journeys','Titus',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Hexen','GT Interactive Software',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Hey You, Pikachu!','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Hot Wheels Turbo Racing','Electronic Arts',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Hybrid Heaven','Konami',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Hydro Thunder','Midway Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Iggy''s Reckin'' Balls','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('In-Fisherman Bass Hunter 64','Take-Two',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Indiana Jones and the Infernal Machine','LucasArts',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Indy Racing 2000','Infogrames',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('International Superstar Soccer 64','Konami',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('International Superstar Soccer 2000','Konami',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('International Superstar Soccer ''98','Konami',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('International Track & Field 2000','Konami',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Jeopardy!','GameTek',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Jeremy McGrath Supercross 2000','Acclaim',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Jet Force Gemini','Rare',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('John Romero''s Daikatana','Kemco',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Ken Griffey Jr.''s Slugfest','Nintendo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Killer Instinct Gold','Nintendo',1996);
INSERT INTO games(Name,Publisher,Year) VALUES ('Kirby 64: The Crystal Shards','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Knife Edge: Nose Gunner','Kemco',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Knockout Kings 2000','EA Sports',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Kobe Bryant in NBA Courtside','Nintendo',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Legend of Zelda: Majora''s Mask, The','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Legend of Zelda: Ocarina of Time, The','Nintendo',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Lego Racers','Lego Media',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Lode Runner 3-D','Infogrames',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mace: The Dark Age','Midway Games',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Madden Football 64','EA Sports',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Madden NFL 2000','EA Sports',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Madden NFL 2001','EA Sports',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Madden NFL 2002','EA Sports',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Madden NFL ''99','EA Sports',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Magical Tetris Challenge','Capcom',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Major League Baseball Featuring Ken Griffey, Jr.','Nintendo',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mario Golf','Nintendo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mario Kart 64','Nintendo',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mario Party','Nintendo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mario Party 2','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mario Party 3','Nintendo',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mario Tennis','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mega Man 64','Capcom',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mia Hamm Soccer 64','SouthPeak Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mickey''s Speedway USA','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Micro Machines 64 Turbo','Midway Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Midway''s Greatest Arcade Hits: Volume 1','Midway Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mike Piazza''s Strike Zone','GT Interactive Software',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Milo''s Astro Lanes','Crave Entertainment',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mischief Makers','Nintendo',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mission: Impossible','Ocean Software',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Monaco Grand Prix','Ubisoft',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Monopoly','Hasbro Interactive',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Monster Truck Madness 64','Rockstar Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mortal Kombat 4','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mortal Kombat Mythologies: Sub-Zero','Midway Games',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mortal Kombat Trilogy','Midway Games',1996);
INSERT INTO games(Name,Publisher,Year) VALUES ('Ms. Pac-Man: Maze Madness','Namco',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Multi-Racing Championship','Ocean Software',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Mystical Ninja Starring Goemon','Konami',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Nagano Winter Olympics ''98','Konami',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Namco Museum 64','Namco',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('NASCAR 2000','EA Sports',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('NASCAR ''99','EA Sports',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('NBA Courtside 2 Featuring Kobe Bryant','Nintendo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('NBA Hangtime','Midway Games',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('NBA In the Zone 2000','Konami',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('NBA In The Zone ''98','Konami',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('NBA In The Zone ''99','Konami',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('NBA Jam 2000','Acclaim',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('NBA Jam ''99','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('NBA Live 2000','EA Sports',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('NBA Live ''99','EA Sports',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('NBA Showtime: NBA on NBC','Midway Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('New Tetris, The','Nintendo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('NFL Blitz','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('NFL Blitz 2000','Midway Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('NFL Blitz 2001','Midway Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('NFL Blitz: Special Edition','Midway Games',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('NFL Quarterback Club 98','Acclaim',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('NFL Quarterback Club 2000','Acclaim',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('NFL Quarterback Club 2001','Acclaim',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('NFL Quarterback Club ''99','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('NHL ''99','EA Sports',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('NHL Blades of Steel ''99','Konami',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('NHL Breakaway ''98','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('NHL Breakaway ''99','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Nightmare Creatures','Activision',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Nuclear Strike 64','THQ',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Off Road Challenge','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Ogre Battle 64: Person of Lordly Caliber','Atlus',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Olympic Hockey ''98','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Paper Mario','Nintendo',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Paperboy','Midway Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Penny Racers','THQ',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Perfect Dark','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('PGA European Tour','Infogrames',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Pilotwings 64','Nintendo',1996);
INSERT INTO games(Name,Publisher,Year) VALUES ('Pok�mon Puzzle League','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Pok�mon Snap','Nintendo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Pok�mon Stadium','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Pok�mon Stadium 2','Nintendo',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Polaris SnoCross','Vatical Entertainment',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Power Rangers: Lightspeed Rescue','THQ',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Powerpuff Girls: Chemical X-Traction, The','Bam Entertainment',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Quake','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Quake II','Activision',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Quest 64','THQ',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Rally Challenge 2000','SouthPeak Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Rampage 2: Universal Tour','Midway Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Rampage World Tour','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Rat Attack!','Mindscape',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Rayman 2: The Great Escape','Ubisoft',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Razor Freestyle Scooter','Crave Entertainment',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Re-Volt','Acclaim',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Ready 2 Rumble Boxing','Midway Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Ready 2 Rumble Boxing: Round 2','Midway Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Resident Evil 2','Capcom',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Ridge Racer 64','Nintendo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Road Rash 64','THQ',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Roadsters','Titus Software',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Robotron 64','Crave Entertainment',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Rocket: Robot on Wheels','Ubisoft',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Rugrats in Paris: The Movie','THQ',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Rugrats: Scavenger Hunt','THQ',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Rush 2: Extreme Racing USA','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('S.C.A.R.S.','Ubisoft',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('San Francisco Rush 2049','Midway Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('San Francisco Rush: Extreme Racing','Midway Games',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Scooby-Doo! Classic Creep Capers','THQ',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Sesame Street: Elmo''s Letter Adventure','NewKidCo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Sesame Street: Elmo''s Number Journey','NewKidCo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Shadow Man','Acclaim',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Shadowgate 64: Trials of the Four Towers','Kemco',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Snowboard Kids','Atlus',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Snowboard Kids 2','Atlus',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('South Park','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('South Park Rally','Acclaim',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('South Park: Chef''s Luv Shack','Acclaim',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Space Invaders','Activision',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Space Station Silicon Valley','Take-Two',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Spider-Man','Activision',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Star Fox 64','Nintendo',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Star Soldier: Vanishing Earth','Electro Brain',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Star Wars Episode I: Racer','LucasArts',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Star Wars: Episode I: Battle for Naboo','LucasArts',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Star Wars: Rogue Squadron','LucasArts',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Star Wars: Shadows of the Empire','LucasArts',1996);
INSERT INTO games(Name,Publisher,Year) VALUES ('Starcraft 64','Blizzard Entertainment',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Starshot: Space Circus Fever','Infogrames',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Stunt Racer 64','Midway Games',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Super Bowling','UFO Interactive Games',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Super Mario 64','Nintendo',1996);
INSERT INTO games(Name,Publisher,Year) VALUES ('Super Smash Bros.','Nintendo',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Supercross 2000','EA Sports',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Superman','Titus Software',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Tarzan','Activision',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Tetrisphere','Nintendo',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Tigger''s Honey Hunt','NewKidCo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Tom and Jerry in Fists of Furry','NewKidCo',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Tom Clancy''s Rainbow Six','Red Storm Entertainment',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Tonic Trouble','Ubisoft',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Tony Hawk''s Pro Skater','Activision',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Tony Hawk''s Pro Skater 2','Activision',2001);
INSERT INTO games(Name,Publisher,Year) VALUES ('Tony Hawk''s Pro Skater 3','Activision',2002);
INSERT INTO games(Name,Publisher,Year) VALUES ('Top Gear Overdrive','Kemco',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Top Gear Rally','Kemco',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Top Gear Rally 2','Kemco',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Top Gear: Hyper Bike','Kemco',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Toy Story 2: Buzz Lightyear to the Rescue','Activision',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Transformers: Beast Wars Transmetals','Bam Entertainment',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Triple Play 2000','EA Sports',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Turok 2: Seeds of Evil','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Turok 3: Shadow of Oblivion','Acclaim',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Turok: Dinosaur Hunter','Acclaim',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Turok: Rage Wars','Acclaim',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Twisted Edge: Extreme Snowboarding','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('V-Rally Edition ''99','Infogrames',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Vigilante 8','Activision',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Vigilante 8: 2nd Offense','Activision',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('Virtual Chess 64','Titus Software',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Virtual Pool 64','Crave Entertainment',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Waialae Country Club: True Golf Classics','Nintendo',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('War Gods','Midway Games',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('Wave Race 64','Nintendo',1996);
INSERT INTO games(Name,Publisher,Year) VALUES ('Wayne Gretzky''s 3D Hockey','Midway Games',1996);
INSERT INTO games(Name,Publisher,Year) VALUES ('Wayne Gretzky''s 3D Hockey ''98','Midway Games',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('WCW Backstage Assault','Electronic Arts',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('WCW Mayhem','EA Sports',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('WCW Nitro','THQ',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('WCW vs. nWo: World Tour','THQ',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('WCW/nWo Revenge','THQ',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Wetrix','Ocean Software',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('Wheel of Fortune','GameTek',1997);
INSERT INTO games(Name,Publisher,Year) VALUES ('WinBack: Covert Operations','Koei',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('WipeOut 64','Midway Games',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('World Cup ''98','EA Sports',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('World Driver Championship','Midway Games',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Worms: Armageddon','Infogrames',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('WWF Attitude','Acclaim',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('WWF No Mercy','THQ',2000);
INSERT INTO games(Name,Publisher,Year) VALUES ('WWF War Zone','Acclaim',1998);
INSERT INTO games(Name,Publisher,Year) VALUES ('WWF WrestleMania 2000','THQ',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Xena: Warrior Princess - The Talisman of Fate','Titus Software',1999);
INSERT INTO games(Name,Publisher,Year) VALUES ('Yoshi''s Story','Nintendo',1998);